#!/bin/bash

printf "\033[0;37m[\033[0;31m*\033[0;37m] Welcome to the Hunter-Toolkit!\n"

sleep 1.25

printf "\033[0;37m[\033[0;31m*\033[0;37m] Starting the installer ...\n"

sleep 1.25

if ! command -v pip &> /dev/null; then
        sudo apt-get update && sudo apt-get install python3 python3-pip 

elif ! command -v curl &> /dev/null; then
        sudo apt-get update && sudo apt-get install curl
fi

if [ -f "req/requirements.txt" ]; then
        pip install -r req/requirements.txt
fi

printf "\033[0;37m[\033[0;32m+\033[0;37m] Hunter-Toolkit is now ready to use ...\n"

sleep 1.25

printf "\033[0;37m[\033[0;31m*\033[0;37m] Do you want to start the Hunter-Toolkit? y/n "

read CHOICE

if [[ $CHOICE == "y" || $CHOICE == "Y" ]]; then
	printf "\033[0;37m[\033[0;31m*\033[0;37m] Starting the Hunter-Toolkit ...\n"

	sleep 1.25

	python3 gate.py

	exit 0

elif [[ $CHOICE == "n" || $CHOICE == "N" ]]; then
	printf "\033[0;37m[\033[0;31m*\033[0;37m] All right, thank you for choosing the Hunter-Toolkit!\n"

	exit 0
else
	printf "\033[0;37m[\033[0;33m-\033[0;37m] Invalid Input!\n"

	exit 1
fi

exit 0


