#!/bin/bash

cd ..

printf "[*] Welcome to Hunter-Toolkit updater!\n"

sleep 1.25

printf "[*] Removing Hunter-Toolkit ...\n"

sleep 1.25

if [ -d "Hunter-Toolkit" ]; then
	rm -rf Hunter-Toolkit
fi

printf "[*] Done.\n"

sleep 1.25

printf "[*] Check if git is installed ...\n"

sleep 1.25

if ! command -v git &> /dev/null; then
	sudo apt-get update && sudo apt-get install git
fi

printf "[*] Done.\n"

sleep 1.25

printf "[*] Getting Hunter-Toolkit ...\n"

git clone https://github.com/Keyj33k/Hunter-Toolkit.git || (printf "Failed getting Hunter-Toolkit!" && exit 1)

printf "[*] Done.\n"

sleep 1.25

printf "[*] Do you want to start the Hunter-Toolkit? y/n "

read CHOICE

if [[ $CHOICE == "y" || $CHOICE == "Y" ]]; then
        printf "[*] Starting the Hunter-Toolkit ...\n"

        sleep 1.25

        cd Hunter-Toolkit && python3 gate.py

        exit 0
elif [[ $CHOICE == "n" || $CHOICE == "N" ]]; then
        printf "[*] All right, thank you for choosing the Hunter-Toolkit!\n"

        exit 0
else
        printf "[-] Invalid Input!\n"

        exit 1
fi


exit 0
